[package]
name = "Framework"
version = "0.0.0"

[addresses]
algomove = "0xaaa"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
